// Generated from the legacy item-name table; keep item IDs stable.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EssenceEvidence {
    Released,
    Candidate,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EssenceDefinition {
    pub item_id: u16,
    pub name: &'static str,
    pub field: &'static str,
    pub evidence: EssenceEvidence,
}

impl EssenceDefinition {
    pub const ITEM_TABLE_OFFSET: usize = 0x4c72;
    pub const METADATA_OFFSET: usize = 0x380;

    #[must_use]
    pub const fn owned_offset(self) -> usize {
        Self::ITEM_TABLE_OFFSET + self.item_id as usize
    }

    #[must_use]
    pub const fn metadata_offset(self) -> usize {
        self.owned_offset() + Self::METADATA_OFFSET
    }

    #[must_use]
    pub const fn released(self) -> bool {
        matches!(self.evidence, EssenceEvidence::Released)
    }
}

pub const ESSENCES: &[EssenceDefinition] = &[
    EssenceDefinition {
        item_id: 221,
        name: "NOT USED:ITEM_SKILLGET_1",
        field: "essences.not_used_item_skillget_1.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 222,
        name: "NOT USED:ITEM_SKILLGET_2",
        field: "essences.not_used_item_skillget_2.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 223,
        name: "NOT USED:ITEM_SKILLGET_3",
        field: "essences.not_used_item_skillget_3.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 224,
        name: "NOT USED:ITEM_SKILLGET_4",
        field: "essences.not_used_item_skillget_4.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 225,
        name: "NOT USED:ITEM_SKILLGET_5",
        field: "essences.not_used_item_skillget_5.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 226,
        name: "NOT USED:ITEM_SKILLGET_6",
        field: "essences.not_used_item_skillget_6.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 227,
        name: "NOT USED:ITEM_SKILLGET_7",
        field: "essences.not_used_item_skillget_7.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 228,
        name: "NOT USED:ITEM_SKILLGET_8",
        field: "essences.not_used_item_skillget_8.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 229,
        name: "NOT USED:ITEM_SKILLGET_9",
        field: "essences.not_used_item_skillget_9.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 230,
        name: "NOT USED:ITEM_SKILLGET_10",
        field: "essences.not_used_item_skillget_10.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 231,
        name: "NOT USED:ITEM_SKILLGET_11",
        field: "essences.not_used_item_skillget_11.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 232,
        name: "NOT USED:ITEM_SKILLGET_12",
        field: "essences.not_used_item_skillget_12.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 233,
        name: "NOT USED:ITEM_SKILLGET_13",
        field: "essences.not_used_item_skillget_13.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 234,
        name: "NOT USED:ITEM_SKILLGET_14",
        field: "essences.not_used_item_skillget_14.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 235,
        name: "NOT USED:ITEM_SKILLGET_15",
        field: "essences.not_used_item_skillget_15.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 236,
        name: "NOT USED:ITEM_SKILLGET_16",
        field: "essences.not_used_item_skillget_16.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 237,
        name: "NOT USED:ITEM_SKILLGET_17",
        field: "essences.not_used_item_skillget_17.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 238,
        name: "NOT USED:ITEM_SKILLGET_18",
        field: "essences.not_used_item_skillget_18.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 239,
        name: "NOT USED:ITEM_SKILLGET_19",
        field: "essences.not_used_item_skillget_19.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 240,
        name: "NOT USED:ITEM_SKILLGET_20",
        field: "essences.not_used_item_skillget_20.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 241,
        name: "NOT USED:ITEM_SKILLGET_21",
        field: "essences.not_used_item_skillget_21.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 242,
        name: "NOT USED:ITEM_SKILLGET_22",
        field: "essences.not_used_item_skillget_22.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 243,
        name: "NOT USED:ITEM_SKILLGET_23",
        field: "essences.not_used_item_skillget_23.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 244,
        name: "NOT USED:ITEM_SKILLGET_24",
        field: "essences.not_used_item_skillget_24.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 245,
        name: "NOT USED:ITEM_SKILLGET_25",
        field: "essences.not_used_item_skillget_25.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 246,
        name: "NOT USED:ITEM_SKILLGET_26",
        field: "essences.not_used_item_skillget_26.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 247,
        name: "NOT USED:ITEM_SKILLGET_27",
        field: "essences.not_used_item_skillget_27.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 248,
        name: "NOT USED:ITEM_SKILLGET_28",
        field: "essences.not_used_item_skillget_28.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 249,
        name: "NOT USED:ITEM_SKILLGET_29",
        field: "essences.not_used_item_skillget_29.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 250,
        name: "NOT USED:ITEM_SKILLGET_30",
        field: "essences.not_used_item_skillget_30.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 251,
        name: "NOT USED:ITEM_SKILLGET_31",
        field: "essences.not_used_item_skillget_31.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 252,
        name: "NOT USED:ITEM_SKILLGET_32",
        field: "essences.not_used_item_skillget_32.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 253,
        name: "NOT USED:ITEM_SKILLGET_33",
        field: "essences.not_used_item_skillget_33.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 254,
        name: "NOT USED:ITEM_SKILLGET_34",
        field: "essences.not_used_item_skillget_34.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 255,
        name: "NOT USED:ITEM_SKILLGET_35",
        field: "essences.not_used_item_skillget_35.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 256,
        name: "NOT USED:ITEM_SKILLGET_36",
        field: "essences.not_used_item_skillget_36.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 257,
        name: "NOT USED:ITEM_SKILLGET_37",
        field: "essences.not_used_item_skillget_37.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 258,
        name: "NOT USED:ITEM_SKILLGET_38",
        field: "essences.not_used_item_skillget_38.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 259,
        name: "NOT USED:ITEM_SKILLGET_39",
        field: "essences.not_used_item_skillget_39.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 260,
        name: "NOT USED:ITEM_SKILLGET_40",
        field: "essences.not_used_item_skillget_40.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 261,
        name: "NOT USED:ITEM_SKILLGET_41",
        field: "essences.not_used_item_skillget_41.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 262,
        name: "NOT USED:ITEM_SKILLGET_42",
        field: "essences.not_used_item_skillget_42.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 263,
        name: "NOT USED:ITEM_SKILLGET_43",
        field: "essences.not_used_item_skillget_43.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 264,
        name: "NOT USED:ITEM_SKILLGET_44",
        field: "essences.not_used_item_skillget_44.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 265,
        name: "NOT USED:ITEM_SKILLGET_45",
        field: "essences.not_used_item_skillget_45.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 266,
        name: "NOT USED:ITEM_SKILLGET_46",
        field: "essences.not_used_item_skillget_46.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 267,
        name: "NOT USED:ITEM_SKILLGET_47",
        field: "essences.not_used_item_skillget_47.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 268,
        name: "NOT USED:ITEM_SKILLGET_48",
        field: "essences.not_used_item_skillget_48.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 269,
        name: "NOT USED:ITEM_SKILLGET_49",
        field: "essences.not_used_item_skillget_49.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 270,
        name: "NOT USED:ITEM_SKILLGET_50",
        field: "essences.not_used_item_skillget_50.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 271,
        name: "NOT USED:ITEM_SKILLGET_51",
        field: "essences.not_used_item_skillget_51.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 272,
        name: "NOT USED:ITEM_SKILLGET_52",
        field: "essences.not_used_item_skillget_52.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 273,
        name: "NOT USED:ITEM_SKILLGET_53",
        field: "essences.not_used_item_skillget_53.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 274,
        name: "NOT USED:ITEM_SKILLGET_54",
        field: "essences.not_used_item_skillget_54.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 275,
        name: "NOT USED:ITEM_SKILLGET_55",
        field: "essences.not_used_item_skillget_55.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 276,
        name: "NOT USED:ITEM_SKILLGET_56",
        field: "essences.not_used_item_skillget_56.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 277,
        name: "NOT USED:ITEM_SKILLGET_57",
        field: "essences.not_used_item_skillget_57.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 278,
        name: "NOT USED:ITEM_SKILLGET_58",
        field: "essences.not_used_item_skillget_58.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 279,
        name: "NOT USED:ITEM_SKILLGET_59",
        field: "essences.not_used_item_skillget_59.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 280,
        name: "NOT USED:ITEM_SKILLGET_60",
        field: "essences.not_used_item_skillget_60.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 281,
        name: "NOT USED:ITEM_SKILLGET_61",
        field: "essences.not_used_item_skillget_61.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 282,
        name: "NOT USED:ITEM_SKILLGET_62",
        field: "essences.not_used_item_skillget_62.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 283,
        name: "NOT USED:ITEM_SKILLGET_63",
        field: "essences.not_used_item_skillget_63.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 284,
        name: "NOT USED:ITEM_SKILLGET_64",
        field: "essences.not_used_item_skillget_64.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 285,
        name: "NOT USED:ITEM_SKILLGET_65",
        field: "essences.not_used_item_skillget_65.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 286,
        name: "NOT USED:ITEM_SKILLGET_66",
        field: "essences.not_used_item_skillget_66.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 287,
        name: "NOT USED:ITEM_SKILLGET_67",
        field: "essences.not_used_item_skillget_67.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 288,
        name: "NOT USED:ITEM_SKILLGET_68",
        field: "essences.not_used_item_skillget_68.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 289,
        name: "NOT USED:ITEM_SKILLGET_69",
        field: "essences.not_used_item_skillget_69.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 290,
        name: "NOT USED:ITEM_SKILLGET_70",
        field: "essences.not_used_item_skillget_70.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 291,
        name: "NOT USED:ITEM_SKILLGET_71",
        field: "essences.not_used_item_skillget_71.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 292,
        name: "NOT USED:ITEM_SKILLGET_72",
        field: "essences.not_used_item_skillget_72.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 293,
        name: "NOT USED:ITEM_SKILLGET_73",
        field: "essences.not_used_item_skillget_73.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 294,
        name: "NOT USED:ITEM_SKILLGET_74",
        field: "essences.not_used_item_skillget_74.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 295,
        name: "NOT USED:ITEM_SKILLGET_75",
        field: "essences.not_used_item_skillget_75.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 296,
        name: "NOT USED:ITEM_SKILLGET_76",
        field: "essences.not_used_item_skillget_76.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 297,
        name: "NOT USED:ITEM_SKILLGET_77",
        field: "essences.not_used_item_skillget_77.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 298,
        name: "NOT USED:ITEM_SKILLGET_78",
        field: "essences.not_used_item_skillget_78.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 299,
        name: "NOT USED:ITEM_SKILLGET_79",
        field: "essences.not_used_item_skillget_79.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 300,
        name: "NOT USED:ITEM_SKILLGET_80",
        field: "essences.not_used_item_skillget_80.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 301,
        name: "NOT USED:ITEM_SKILLGET_81",
        field: "essences.not_used_item_skillget_81.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 302,
        name: "NOT USED:ITEM_SKILLGET_82",
        field: "essences.not_used_item_skillget_82.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 303,
        name: "NOT USED:ITEM_SKILLGET_83",
        field: "essences.not_used_item_skillget_83.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 304,
        name: "NOT USED:ITEM_SKILLGET_84",
        field: "essences.not_used_item_skillget_84.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 305,
        name: "NOT USED:ITEM_SKILLGET_85",
        field: "essences.not_used_item_skillget_85.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 306,
        name: "NOT USED:ITEM_SKILLGET_86",
        field: "essences.not_used_item_skillget_86.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 307,
        name: "NOT USED:ITEM_SKILLGET_87",
        field: "essences.not_used_item_skillget_87.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 308,
        name: "NOT USED:ITEM_SKILLGET_88",
        field: "essences.not_used_item_skillget_88.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 309,
        name: "NOT USED:ITEM_SKILLGET_89",
        field: "essences.not_used_item_skillget_89.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 310,
        name: "NOT USED:ITEM_SKILLGET_90",
        field: "essences.not_used_item_skillget_90.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 311,
        name: "Khonsu's Essence",
        field: "essences.khonsu.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 312,
        name: "Zeus's Essence",
        field: "essences.zeus.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 313,
        name: "Odin's Essence",
        field: "essences.odin.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 314,
        name: "Mitra's Essence",
        field: "essences.mitra.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 315,
        name: "Atavaka's Essence",
        field: "essences.atavaka.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 316,
        name: "Horus's Essence",
        field: "essences.horus.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 317,
        name: "Thoth's Essence",
        field: "essences.thoth.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 318,
        name: "Khonsu Ra's Essence",
        field: "essences.khonsu_ra.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 319,
        name: "Vishnu's Essence",
        field: "essences.vishnu.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 320,
        name: "Baal's Essence",
        field: "essences.baal.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 321,
        name: "Demeter's Essence",
        field: "essences.demeter.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 322,
        name: "Anahita's Essence",
        field: "essences.anahita.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 323,
        name: "Lakshmi's Essence",
        field: "essences.lakshmi.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 324,
        name: "Norn's Essence",
        field: "essences.norn.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 325,
        name: "Idun's Essence",
        field: "essences.idun.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 326,
        name: "Sarasvati's Essence",
        field: "essences.sarasvati.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 327,
        name: "Ishtar's Essence",
        field: "essences.ishtar.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 328,
        name: "Scathach's Essence",
        field: "essences.scathach.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 329,
        name: "Parvati's Essence",
        field: "essences.parvati.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 330,
        name: "Ame-no-Uzume's Essence",
        field: "essences.ame_no_uzume.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 331,
        name: "Fortuna's Essence",
        field: "essences.fortuna.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 332,
        name: "Maria's Essence",
        field: "essences.maria.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 333,
        name: "Artemis's Essence",
        field: "essences.artemis.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 334,
        name: "Hanuman's Essence",
        field: "essences.hanuman.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 335,
        name: "Fionn's Essence",
        field: "essences.fionn.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 336,
        name: "Cu Chulainn's Essence",
        field: "essences.cu_chulainn.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 337,
        name: "Kurama Tengu's Essence",
        field: "essences.kurama_tengu.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 338,
        name: "Amanozako's Essence",
        field: "essences.amanozako.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 339,
        name: "Koppa Tengu's Essence",
        field: "essences.koppa_tengu.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 340,
        name: "Apsaras's Essence",
        field: "essences.apsaras.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 341,
        name: "Agathion's Essence",
        field: "essences.agathion.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 342,
        name: "Mandrake's Essence",
        field: "essences.mandrake.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 343,
        name: "Titania's Essence",
        field: "essences.titania.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 344,
        name: "Oberon's Essence",
        field: "essences.oberon.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 345,
        name: "Silky's Essence",
        field: "essences.silky.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 346,
        name: "Setanta's Essence",
        field: "essences.setanta.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 347,
        name: "Kelpie's Essence",
        field: "essences.kelpie.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 348,
        name: "High Pixie's Essence",
        field: "essences.high_pixie.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 349,
        name: "Jack-o'-Lantern's Essence",
        field: "essences.jack_o_lantern.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 350,
        name: "Jack Frost's Essence",
        field: "essences.jack_frost.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 351,
        name: "Pixie's Essence",
        field: "essences.pixie.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 352,
        name: "Queen Medb's Essence",
        field: "essences.queen_medb.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 353,
        name: "Succubus's Essence",
        field: "essences.succubus.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 354,
        name: "Kaiwan's Essence",
        field: "essences.kaiwan.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 355,
        name: "Lilim's Essence",
        field: "essences.lilim.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 356,
        name: "Incubus's Essence",
        field: "essences.incubus.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 357,
        name: "Mokoi's Essence",
        field: "essences.mokoi.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 358,
        name: "Sandman's Essence",
        field: "essences.sandman.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 359,
        name: "Lilith's Essence",
        field: "essences.lilith_359.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 360,
        name: "Black Frost's Essence",
        field: "essences.black_frost.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 361,
        name: "Nuwa's Essence",
        field: "essences.nuwa_361.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 362,
        name: "Amon's Essence",
        field: "essences.amon.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 363,
        name: "Mara's Essence",
        field: "essences.mara.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 364,
        name: "Mephisto's Essence",
        field: "essences.mephisto.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 365,
        name: "Chi You's Essence",
        field: "essences.chi_you.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 366,
        name: "Surt's Essence",
        field: "essences.surt.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 367,
        name: "Beelzebub's Essence",
        field: "essences.beelzebub.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 368,
        name: "Arioch's Essence",
        field: "essences.arioch.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 369,
        name: "Belial's Essence",
        field: "essences.belial.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 370,
        name: "Abaddon's Essence",
        field: "essences.abaddon.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 371,
        name: "Moloch's Essence",
        field: "essences.moloch.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 372,
        name: "Belphegor's Essence",
        field: "essences.belphegor.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 373,
        name: "King Frost's Essence",
        field: "essences.king_frost.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 374,
        name: "Mithras's Essence",
        field: "essences.mithras.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 375,
        name: "Loki's Essence",
        field: "essences.loki.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 376,
        name: "Huang Long's Essence",
        field: "essences.huang_long.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 377,
        name: "Quetzalcoatl's Essence",
        field: "essences.quetzalcoatl.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 378,
        name: "Qinglong's Essence",
        field: "essences.qinglong.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 379,
        name: "Xuanwu's Essence",
        field: "essences.xuanwu.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 380,
        name: "Ananta's Essence",
        field: "essences.ananta.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 381,
        name: "Yamata-no-Orochi's Essence",
        field: "essences.yamata_no_orochi.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 382,
        name: "Naga Raja's Essence",
        field: "essences.naga_raja.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 383,
        name: "Yurlungur's Essence",
        field: "essences.yurlungur.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 384,
        name: "Naga's Essence",
        field: "essences.naga.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 385,
        name: "Vasuki's Essence",
        field: "essences.vasuki.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 386,
        name: "Seth's Essence",
        field: "essences.seth.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 387,
        name: "Basilisk's Essence",
        field: "essences.basilisk.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 388,
        name: "Aitvaras's Essence",
        field: "essences.aitvaras.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 389,
        name: "Hydra's Essence",
        field: "essences.hydra.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 390,
        name: "Fafnir's Essence",
        field: "essences.fafnir.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 391,
        name: "Barong's Essence",
        field: "essences.barong.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 392,
        name: "Anubis's Essence",
        field: "essences.anubis.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 393,
        name: "Makami's Essence",
        field: "essences.makami.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 394,
        name: "Baihu's Essence",
        field: "essences.baihu.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 395,
        name: "Chimera's Essence",
        field: "essences.chimera.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 396,
        name: "Cironnup's Essence",
        field: "essences.cironnup.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 397,
        name: "Shiisaa's Essence",
        field: "essences.shiisaa.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 398,
        name: "Cerberus's Essence",
        field: "essences.cerberus.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 399,
        name: "Orthrus's Essence",
        field: "essences.orthrus.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 400,
        name: "Loup-garou's Essence",
        field: "essences.loup_garou.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 401,
        name: "Nekomata's Essence",
        field: "essences.nekomata.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 402,
        name: "Inugami's Essence",
        field: "essences.inugami.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 403,
        name: "Orobas's Essence",
        field: "essences.orobas.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 404,
        name: "Cait Sith's Essence",
        field: "essences.cait_sith.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 405,
        name: "Bugs's Essence",
        field: "essences.bugs.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 406,
        name: "Nue's Essence",
        field: "essences.nue.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 407,
        name: "Bicorn's Essence",
        field: "essences.bicorn.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 408,
        name: "Mothman's Essence",
        field: "essences.mothman.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 409,
        name: "Hayataro's Essence",
        field: "essences.hayataro.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 410,
        name: "Flaemis's Essence",
        field: "essences.flaemis.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 411,
        name: "Aquans's Essence",
        field: "essences.aquans.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 412,
        name: "Aeros's Essence",
        field: "essences.aeros.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 413,
        name: "Erthys's Essence",
        field: "essences.erthys.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 414,
        name: "NOT USED:ITEM_UTSUSEMI_104",
        field: "essences.not_used_item_utsusemi_104.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 415,
        name: "NOT USED:ITEM_UTSUSEMI_105",
        field: "essences.not_used_item_utsusemi_105.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 416,
        name: "NOT USED:ITEM_UTSUSEMI_106",
        field: "essences.not_used_item_utsusemi_106.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 417,
        name: "NOT USED:ITEM_UTSUSEMI_107",
        field: "essences.not_used_item_utsusemi_107.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 418,
        name: "Black Ooze's Essence",
        field: "essences.black_ooze.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 419,
        name: "Legion's Essence",
        field: "essences.legion.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 420,
        name: "Slime's Essence",
        field: "essences.slime.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 421,
        name: "Shiva's Essence",
        field: "essences.shiva.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 422,
        name: "Mot's Essence",
        field: "essences.mot.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 423,
        name: "Zaou-Gongen's Essence",
        field: "essences.zaou_gongen.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 424,
        name: "Asura's Essence",
        field: "essences.asura.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 425,
        name: "Chernobog's Essence",
        field: "essences.chernobog.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 426,
        name: "Dionysus's Essence",
        field: "essences.dionysus.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 427,
        name: "Danu's Essence",
        field: "essences.danu.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 428,
        name: "Inanna's Essence",
        field: "essences.inanna.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 429,
        name: "Kali's Essence",
        field: "essences.kali.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 430,
        name: "Cybele's Essence",
        field: "essences.cybele.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 431,
        name: "Skadi's Essence",
        field: "essences.skadi.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 432,
        name: "Isis's Essence",
        field: "essences.isis.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 433,
        name: "Kikuri-Hime's Essence",
        field: "essences.kikuri_hime.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 434,
        name: "Hariti's Essence",
        field: "essences.hariti.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 435,
        name: "Nuwa's Essence",
        field: "essences.nuwa_435.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 436,
        name: "Alilat's Essence",
        field: "essences.alilat.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 437,
        name: "Thor's Essence",
        field: "essences.thor.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 438,
        name: "Futsunushi's Essence",
        field: "essences.futsunushi.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 439,
        name: "Attis's Essence",
        field: "essences.attis.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 440,
        name: "Bishamonten's Essence",
        field: "essences.bishamonten.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 441,
        name: "Jikokuten's Essence",
        field: "essences.jikokuten.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 442,
        name: "Koumokuten's Essence",
        field: "essences.koumokuten.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 443,
        name: "Zouchouten's Essence",
        field: "essences.zouchouten.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 444,
        name: "Arahabaki's Essence",
        field: "essences.arahabaki.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 445,
        name: "Oyamatsumi's Essence",
        field: "essences.oyamatsumi.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 446,
        name: "Kushinada-Hime's Essence",
        field: "essences.kushinada_hime.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 447,
        name: "Sukuna-Hikona's Essence",
        field: "essences.sukuna_hikona.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 448,
        name: "Okuninushi's Essence",
        field: "essences.okuninushi.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 449,
        name: "Take-Minakata's Essence",
        field: "essences.take_minakata.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 450,
        name: "Ganesha's Essence",
        field: "essences.ganesha.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 451,
        name: "Siegfried's Essence",
        field: "essences.siegfried.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 452,
        name: "Valkyrie's Essence",
        field: "essences.valkyrie.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 453,
        name: "Yoshitsune's Essence",
        field: "essences.yoshitsune.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 454,
        name: "Neko Shogun's Essence",
        field: "essences.neko_shogun.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 455,
        name: "Mada's Essence",
        field: "essences.mada.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 456,
        name: "Girimekhala's Essence",
        field: "essences.girimekhala.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 457,
        name: "Pazuzu's Essence",
        field: "essences.pazuzu.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 458,
        name: "Mishaguji's Essence",
        field: "essences.mishaguji.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 459,
        name: "Baphomet's Essence",
        field: "essences.baphomet.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 460,
        name: "Lahmu's Essence",
        field: "essences.lahmu.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 461,
        name: "Abdiel's Essence",
        field: "essences.abdiel_461.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 462,
        name: "Metatron's Essence",
        field: "essences.metatron.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 463,
        name: "Michael's Essence",
        field: "essences.michael.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 464,
        name: "Gabriel's Essence",
        field: "essences.gabriel.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 465,
        name: "Sraosha's Essence",
        field: "essences.sraosha.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 466,
        name: "Raphael's Essence",
        field: "essences.raphael.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 467,
        name: "Sandalphon's Essence",
        field: "essences.sandalphon.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 468,
        name: "Uriel's Essence",
        field: "essences.uriel.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 469,
        name: "Camael's Essence",
        field: "essences.camael.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 470,
        name: "Melchizedek's Essence",
        field: "essences.melchizedek.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 471,
        name: "Throne's Essence",
        field: "essences.throne.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 472,
        name: "Dominion's Essence",
        field: "essences.dominion.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 473,
        name: "Power's Essence",
        field: "essences.power.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 474,
        name: "Principality's Essence",
        field: "essences.principality.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 475,
        name: "Archangel's Essence",
        field: "essences.archangel.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 476,
        name: "Angel's Essence",
        field: "essences.angel.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 477,
        name: "Abdiel's Essence",
        field: "essences.abdiel_477.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 478,
        name: "Adramelech's Essence",
        field: "essences.adramelech.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 479,
        name: "Flauros's Essence",
        field: "essences.flauros.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 480,
        name: "Nebiros's Essence",
        field: "essences.nebiros.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 481,
        name: "Berith's Essence",
        field: "essences.berith.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 482,
        name: "Ose's Essence",
        field: "essences.ose.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 483,
        name: "Eligor's Essence",
        field: "essences.eligor.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 484,
        name: "Forneus's Essence",
        field: "essences.forneus.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 485,
        name: "Andras's Essence",
        field: "essences.andras.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 486,
        name: "Decarabia's Essence",
        field: "essences.decarabia.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 487,
        name: "Garuda's Essence",
        field: "essences.garuda.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 488,
        name: "Zhuque's Essence",
        field: "essences.zhuque.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 489,
        name: "Yatagarasu's Essence",
        field: "essences.yatagarasu.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 490,
        name: "Jatayu's Essence",
        field: "essences.jatayu.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 491,
        name: "Feng Huang's Essence",
        field: "essences.feng_huang.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 492,
        name: "Thunderbird's Essence",
        field: "essences.thunderbird.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 493,
        name: "Anzu's Essence",
        field: "essences.anzu.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 494,
        name: "Zhen's Essence",
        field: "essences.zhen.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 495,
        name: "Muu Shuwuu's Essence",
        field: "essences.muu_shuwuu.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 496,
        name: "Onmoraki's Essence",
        field: "essences.onmoraki.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 497,
        name: "Cleopatra's Essence",
        field: "essences.cleopatra.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 498,
        name: "Rangda's Essence",
        field: "essences.rangda.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 499,
        name: "Dakini's Essence",
        field: "essences.dakini.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 500,
        name: "Atropos's Essence",
        field: "essences.atropos.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 501,
        name: "Yakshini's Essence",
        field: "essences.yakshini.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 502,
        name: "Lachesis's Essence",
        field: "essences.lachesis.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 503,
        name: "Clotho's Essence",
        field: "essences.clotho.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 504,
        name: "Manananggal's Essence",
        field: "essences.manananggal.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 505,
        name: "Lamia's Essence",
        field: "essences.lamia.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 506,
        name: "Mermaid's Essence",
        field: "essences.mermaid.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 507,
        name: "Leanan Sidhe's Essence",
        field: "essences.leanan_sidhe.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 508,
        name: "Ongyo-Ki's Essence",
        field: "essences.ongyo_ki.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 509,
        name: "Shiki-Ouji's Essence",
        field: "essences.shiki_ouji.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 510,
        name: "Sui-Ki's Essence",
        field: "essences.sui_ki.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 511,
        name: "Fuu-Ki's Essence",
        field: "essences.fuu_ki.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 512,
        name: "Kin-Ki's Essence",
        field: "essences.kin_ki.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 513,
        name: "Azumi's Essence",
        field: "essences.azumi.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 514,
        name: "Ippon-Datara's Essence",
        field: "essences.ippon_datara.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 515,
        name: "Daemon's Essence",
        field: "essences.daemon.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 516,
        name: "Oni's Essence",
        field: "essences.oni.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 517,
        name: "Hecatoncheires's Essence",
        field: "essences.hecatoncheires.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 518,
        name: "Loa's Essence",
        field: "essences.loa.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 519,
        name: "Rakshasa's Essence",
        field: "essences.rakshasa.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 520,
        name: "Turdak's Essence",
        field: "essences.turdak.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 521,
        name: "Macabre's Essence",
        field: "essences.macabre.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 522,
        name: "Kaya-no-Hime's Essence",
        field: "essences.kaya_no_hime.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 523,
        name: "Tsuchigumo's Essence",
        field: "essences.tsuchigumo.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 524,
        name: "Narcissus's Essence",
        field: "essences.narcissus.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 525,
        name: "Hua Po's Essence",
        field: "essences.hua_po.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 526,
        name: "Koropokkur's Essence",
        field: "essences.koropokkur.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 527,
        name: "Sudama's Essence",
        field: "essences.sudama.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 528,
        name: "Kodama's Essence",
        field: "essences.kodama.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 529,
        name: "Pisaca's Essence",
        field: "essences.pisaca.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 530,
        name: "Kumbhanda's Essence",
        field: "essences.kumbhanda.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 531,
        name: "Poltergeist's Essence",
        field: "essences.poltergeist.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 532,
        name: "Obariyon's Essence",
        field: "essences.obariyon.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 533,
        name: "Preta's Essence",
        field: "essences.preta.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 534,
        name: "Trumpeter's Essence",
        field: "essences.trumpeter.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 535,
        name: "Mother Harlot's Essence",
        field: "essences.mother_harlot.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 536,
        name: "Black Rider's Essence",
        field: "essences.black_rider.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 537,
        name: "Red Rider's Essence",
        field: "essences.red_rider.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 538,
        name: "White Rider's Essence",
        field: "essences.white_rider.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 539,
        name: "Alice's Essence",
        field: "essences.alice.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 540,
        name: "Hell Biker's Essence",
        field: "essences.hell_biker.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 541,
        name: "Daisoujou's Essence",
        field: "essences.daisoujou.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 542,
        name: "Pale Rider's Essence",
        field: "essences.pale_rider.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 543,
        name: "Matador's Essence",
        field: "essences.matador.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 544,
        name: "Aogami Type-1 Essence",
        field: "essences.aogami_type_1.owned",
        evidence: EssenceEvidence::Released,
    },
    EssenceDefinition {
        item_id: 545,
        name: "Aogami Type-2 Essence",
        field: "essences.aogami_type_2.owned",
        evidence: EssenceEvidence::Released,
    },
    EssenceDefinition {
        item_id: 546,
        name: "Aogami Type-3 Essence",
        field: "essences.aogami_type_3.owned",
        evidence: EssenceEvidence::Released,
    },
    EssenceDefinition {
        item_id: 547,
        name: "Aogami Type-4 Essence",
        field: "essences.aogami_type_4.owned",
        evidence: EssenceEvidence::Released,
    },
    EssenceDefinition {
        item_id: 548,
        name: "Aogami Type-5 Essence",
        field: "essences.aogami_type_5.owned",
        evidence: EssenceEvidence::Released,
    },
    EssenceDefinition {
        item_id: 549,
        name: "Aogami Type-6 Essence",
        field: "essences.aogami_type_6.owned",
        evidence: EssenceEvidence::Released,
    },
    EssenceDefinition {
        item_id: 550,
        name: "Aogami Type-7 Essence",
        field: "essences.aogami_type_7.owned",
        evidence: EssenceEvidence::Released,
    },
    EssenceDefinition {
        item_id: 551,
        name: "Aogami Type-8 Essence",
        field: "essences.aogami_type_8.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 552,
        name: "Aogami Type-9 Essence",
        field: "essences.aogami_type_9.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 553,
        name: "Aogami Type-10 Essence",
        field: "essences.aogami_type_10.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 554,
        name: "Aogami Type-0 Essence",
        field: "essences.aogami_type_0.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 555,
        name: "Demi-fiend's Essence",
        field: "essences.demi_fiend.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 556,
        name: "Aogami Type-A Essence",
        field: "essences.aogami_type_a.owned",
        evidence: EssenceEvidence::Released,
    },
    EssenceDefinition {
        item_id: 557,
        name: "Aogami Type-B Essence",
        field: "essences.aogami_type_b.owned",
        evidence: EssenceEvidence::Released,
    },
    EssenceDefinition {
        item_id: 558,
        name: "Aogami Type-C Essence",
        field: "essences.aogami_type_c.owned",
        evidence: EssenceEvidence::Released,
    },
    EssenceDefinition {
        item_id: 559,
        name: "Aogami Type-D Essence",
        field: "essences.aogami_type_d.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 560,
        name: "Satan's Essence",
        field: "essences.satan.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 561,
        name: "Lucifer's Essence",
        field: "essences.lucifer.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 562,
        name: "Dagda's Essence",
        field: "essences.dagda.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 563,
        name: "Kresnik's Essence",
        field: "essences.kresnik.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 564,
        name: "Anansi's Essence",
        field: "essences.anansi.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 565,
        name: "Dis's Essence",
        field: "essences.dis.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 566,
        name: "Efreet's Essence",
        field: "essences.efreet.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 567,
        name: "Nahobeeho's Essence",
        field: "essences.nahobeeho.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 568,
        name: "Vritra's Essence",
        field: "essences.vritra.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 569,
        name: "Nyami Nyami's Essence",
        field: "essences.nyami_nyami.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 570,
        name: "Nozuchi's Essence",
        field: "essences.nozuchi.owned",
        evidence: EssenceEvidence::Released,
    },
    EssenceDefinition {
        item_id: 571,
        name: "Vouivre's Essence",
        field: "essences.vouivre.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 572,
        name: "Zhu Tun She's Essence",
        field: "essences.zhu_tun_she.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 573,
        name: "Samael's Essence",
        field: "essences.samael.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 574,
        name: "Xiezhai's Essence",
        field: "essences.xiezhai.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 575,
        name: "Senri's Essence",
        field: "essences.senri.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 576,
        name: "Unicorn's Essence",
        field: "essences.unicorn.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 577,
        name: "Dormarth's Essence",
        field: "essences.dormarth.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 578,
        name: "Glasya-Labolas's Essence",
        field: "essences.glasya_labolas.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 579,
        name: "Fenrir's Essence",
        field: "essences.fenrir.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 580,
        name: "Peallaidh's Essence",
        field: "essences.peallaidh.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 581,
        name: "Mad Gasser's Essence",
        field: "essences.mad_gasser.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 582,
        name: "Turbo Granny's Essence",
        field: "essences.turbo_granny.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 583,
        name: "Nezha Taizi's Essence",
        field: "essences.nezha_taizi.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 584,
        name: "Masakado's Essence",
        field: "essences.masakado.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 585,
        name: "Saturnus's Essence",
        field: "essences.saturnus.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 586,
        name: "Tzitzimitl's 's Essence",
        field: "essences.tzitzimitl_s.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 587,
        name: "Mastema's Essence",
        field: "essences.mastema.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 588,
        name: "Armaiti's Essence",
        field: "essences.armaiti.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 589,
        name: "Cherub's Essence",
        field: "essences.cherub.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 590,
        name: "Halphas's Essence",
        field: "essences.halphas.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 591,
        name: "Azazel's Essence",
        field: "essences.azazel.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 592,
        name: "Gurulu's Essence",
        field: "essences.gurulu.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 593,
        name: "Karasu Tengu's Essence",
        field: "essences.karasu_tengu.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 594,
        name: "Gremlin's Essence",
        field: "essences.gremlin.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 595,
        name: "Gogmagog's Essence",
        field: "essences.gogmagog.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 596,
        name: "Kudlak's Essence",
        field: "essences.kudlak.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 597,
        name: "Hare of Inaba's Essence",
        field: "essences.hare_of_inaba.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 598,
        name: "Kinmamon's Essence",
        field: "essences.kinmamon.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 599,
        name: "Onyankopon's Essence",
        field: "essences.onyankopon.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 600,
        name: "Amabie's Essence",
        field: "essences.amabie.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 601,
        name: "Lilith's Essence",
        field: "essences.lilith_601.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 602,
        name: "Agrat's Essence",
        field: "essences.agrat.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 603,
        name: "Naamah's Essence",
        field: "essences.naamah.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 604,
        name: "Eisheth's Essence",
        field: "essences.eisheth.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 605,
        name: "Konohana Sakuya's Essence",
        field: "essences.konohana_sakuya.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 606,
        name: "Tsukuyomi's Essence Base",
        field: "essences.tsukuyomi_s_essence_base.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 607,
        name: "Tsukuyomi's Essence Median",
        field: "essences.tsukuyomi_s_essence_median.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 608,
        name: "Tsukuyomi's Essence Ultimus",
        field: "essences.tsukuyomi_s_essence_ultimus.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 609,
        name: "Tao's Essence",
        field: "essences.tao.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 610,
        name: "Yoko's Essence",
        field: "essences.yoko.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 611,
        name: "NOT USED:ITEM_UTSUSEMI_301",
        field: "essences.not_used_item_utsusemi_301.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 612,
        name: "NOT USED:ITEM_UTSUSEMI_302",
        field: "essences.not_used_item_utsusemi_302.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 613,
        name: "NOT USED:ITEM_UTSUSEMI_303",
        field: "essences.not_used_item_utsusemi_303.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 614,
        name: "NOT USED:ITEM_UTSUSEMI_304",
        field: "essences.not_used_item_utsusemi_304.owned",
        evidence: EssenceEvidence::Candidate,
    },
    EssenceDefinition {
        item_id: 615,
        name: "NOT USED:ITEM_UTSUSEMI_305",
        field: "essences.not_used_item_utsusemi_305.owned",
        evidence: EssenceEvidence::Candidate,
    },
];

#[must_use]
pub fn by_field(field: &str) -> Option<EssenceDefinition> {
    ESSENCES.iter().copied().find(|entry| entry.field == field)
}

pub fn released() -> impl Iterator<Item = EssenceDefinition> {
    ESSENCES.iter().copied().filter(|entry| entry.released())
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeSet;

    use super::*;

    #[test]
    fn complete_registry_is_unique_sorted_and_evidence_classified() {
        assert_eq!(ESSENCES.len(), 395);
        assert!(
            ESSENCES
                .windows(2)
                .all(|pair| pair[0].item_id < pair[1].item_id)
        );
        assert_eq!(ESSENCES.first().unwrap().item_id, 221);
        assert_eq!(ESSENCES.last().unwrap().item_id, 615);
        assert_eq!(released().count(), 11);
        assert_eq!(
            ESSENCES
                .iter()
                .filter(|entry| entry.evidence == EssenceEvidence::Candidate)
                .count(),
            384
        );
        let fields = ESSENCES
            .iter()
            .map(|entry| entry.field)
            .collect::<BTreeSet<_>>();
        assert_eq!(fields.len(), ESSENCES.len());
    }

    #[test]
    fn linked_offsets_follow_the_legacy_table_contract() {
        for entry in ESSENCES {
            assert_eq!(
                entry.metadata_offset() - entry.owned_offset(),
                EssenceDefinition::METADATA_OFFSET
            );
            assert_eq!(
                entry.owned_offset(),
                EssenceDefinition::ITEM_TABLE_OFFSET + usize::from(entry.item_id)
            );
        }
    }
}
